### ISSUE TITLE
Gamma will not adjust if set to below 3300K

### ISSUE THREAD

**Issue by Omnicronn** [Tyrrrz/LightBulb#65] opened 2017-12-19 00:19 UTC
The lighting will not adjust if the setting is set to anything below 3300K. The lighting will stay dim if I go below 3300K after setting it to something higher during the same action. However, if the temp was set to something below 3300K and the sunset time is reached, the temperature will not change at all. It seems relevant that 3300K appears to be the dimmest that this application can make my monitor go (dragging it to 2500K produces no visible difference), either because of my monitor's native properties or because of a bug of some sort.

**Comment by Tyrrrz** [comment] 2017-12-19 09:24
Are you running portable or from installer?

**Comment by Omnicronn** [comment] 2017-12-23 01:09
I think I am using the installed version; I used Chocolatey to install Lightbulbv1.6.3.5.

**Comment by mirh** [comment] 2017-12-23 10:16
Just FTR, I have no problems using 1300K on 1.6.3.5

**Comment by Tyrrrz** [comment] 2017-12-23 11:02
Weird. You can try executing the `Manual_Gamma_Registry_Fix.reg` from the portable distro (it should be done automatically by installer though) and see if it fixes it. Otherwise, it could theoretically be a hardware issue since gamma changes are done through GPU.

**Comment by Tyrrrz** [comment] 2018-01-04 14:49
Did you try running the reg file?

**Comment by Tyrrrz** [comment] 2018-01-13 19:09
Closing due to lack of info/reproducibility.

**Closed by Tyrrrz** 2018-01-13 19:09 UTC
Labels: invalid
