### ISSUE TITLE
Light Bulb uses up too much Cpu

### ISSUE THREAD

**Issue by Antosser** [Tyrrrz/LightBulb#204] opened 2021-05-02 14:39 UTC
### Version

last

### Details

LightBulb uses too much CPU (~3%) and I know to fix this:

This small code in C++ can take up to 30% of the CPU:
`int main() while (true) {/* some code */}`

To fix that you can add a sleep function at the end of it like this:
`int main() while (true) {/* some code */ Sleep(5);}`
Now the program is limited to max. 200 cycles/second and will take up around 0.03% of the CPU.
I know that LightBulb is written in C# but please do a quick research.
Thanks!

### Steps to reproduce

1. Open LightBulb
2. Done

**Comment by Tyrrrz** [comment] 2021-05-03 13:24
Duplicate of #198?

**Closed** 2021-05-08 15:13 UTC
Labels: duplicate
