### ISSUE TITLE
Installer .exe is flagged by VirusTotal 

### ISSUE THREAD

**Issue by dncman** [Tyrrrz/LightBulb#203] opened 2021-05-01 12:31 UTC
### Version

2.3

### Details

The installer is flagged as Trojan and malicious on Virustotal.
![image](https://user-images.githubusercontent.com/72662567/116782374-f9505e00-aa88-11eb-95be-6c9cf5168999.png)
https://www.virustotal.com/gui/file/640dbcf52d6364396eb933d74d4a5d6473bab6aaf71d594092810df1a9c01f38/detection 

Portable .exe seems to be ok.
https://www.virustotal.com/gui/file/9f4601b9a9cb0f20baa1b92238dcf81d881404a5113c36257be2368f38cfe12b/detection

### Steps to reproduce

Upload LightBulb-Installer.exe v2.3 to VirusTotal

**Comment by Tyrrrz** [comment] 2021-05-02 01:31
Duplicate of #185 #196

**Closed by Tyrrrz** 2021-05-02 01:31 UTC
Labels: duplicate
