### ISSUE TITLE
VirusTotal reports

### ISSUE THREAD

**Issue by boromyr** [Tyrrrz/LightBulb#235] opened 2022-01-01 21:03 UTC
### Version

2.4.1

### Details

VirusTotal reports 7 malware detections for the file LightBulb.exe [Report](https://www.virustotal.com/gui/file/148a9b566d37794c0c4c0f37b71b077b81da993e17721114b99bbf7f161fd7e4/detection/f-148a9b566d37794c0c4c0f37b71b077b81da993e17721114b99bbf7f161fd7e4-1641062996), while no positives are reported for the installer, 0/68.

### Steps to reproduce

Upload LightBulb.exe to VirusTotal or open the link from previous report. It applies to LightBulb.exe downloaded from Git Action, release version 2.4.1, and maybe also to 2.4.0, but I don't remember well.

**Comment by Tyrrrz** [comment] 2022-01-03 20:17
Duplicate of #232.
Report as false positives if you can, otherwise ignore the reports or don't use LightBulb if you're concerned. I can't influence what random antiviruses think is a virus and I don't have time to deal with it.

**Closed by Tyrrrz** 2022-01-03 20:17 UTC
Labels: invalid
