### ISSUE TITLE
Unable to change warmth for only one monitor.

### ISSUE THREAD

**Issue by respectablenoob-source** [Tyrrrz/LightBulb#231] opened 2021-12-11 08:53 UTC
### Version

2.4.1

### Details

Adjusting warmth affects all monitors.

### Steps to reproduce

Connect monitor to laptop and adjust warmth.

**Comment by Tyrrrz** [comment] 2021-12-11 14:36
Yes, gamma is applied to all monitors. Duplicate of #15.

**Closed by Tyrrrz** 2021-12-11 14:36 UTC
Labels: duplicate
