### ISSUE TITLE
LightBulb 2.3.1 - Virustotal Report (4 Issues)

### ISSUE THREAD

**Issue by jantheodor** [Tyrrrz/LightBulb#196] opened 2021-03-21 07:49 UTC
FYI: https://www.virustotal.com/gui/file/a10966beb62044f5ecfc6dc228e419771133b00f9974b3a6ad9822252cfb0816/detection

**Comment by Tyrrrz** [comment] 2021-03-21 13:20
Duplicate of #185

**Closed by Tyrrrz** 2021-03-21 13:20 UTC
Labels: duplicate
