### ISSUE TITLE
LightBulb disables itself when you open a page in Settings

### ISSUE THREAD

**Issue by fgimian** [Tyrrrz/LightBulb#173] opened 2020-07-31 11:43 UTC
Hey there, I'm not sure if anyone else can reproduce this but I'm running the latest Windows 10 release and latest LightBuilb.

If I open Settings, and then click any item (e.g. System), LightBulb stops dimming the screen.  The app continues to run, but the screen stays bright.  This does not restore itself when I close settings.

My workarounds at the moment are to either restart LightBulb or open LightBuilb and click Preview until it starts working again.

Any ideas?
Fotis

**Comment by Tyrrrz** [comment] 2020-07-31 12:50
That's very weird. My guess is that somehow something else triggers gamma reset when the settings are opened. I can't reproduce this locally.


One workaround is to turn on "gamma polling" in advanced settings.

**Comment by fgimian** [comment] 2020-08-01 01:40
Thanks a lot, yeah it is strange.  It happens consistently here, not sure if it's something on my system that's causing it.  Enabling Gamma Polling does restore the brightness 1 second after I open settings.  I see it flash bright, and then go  dark again, sothat's at least good enough to keep me going.

If I discover what's causing this on my system, I'll be sure to let you know so you can reproduce it.

Thanks a lot
Fotis

**Comment by Tyrrrz** [comment] 2020-08-01 11:22
Thanks. For what it's worth, it doesn't happen for me and has never been reported so far.

**Comment by broizter** [comment] 2020-08-03 20:39
I can reproduce the issue. Open Settings > press System > yellowing/dimming disappears.

**Comment by Tyrrrz** [comment] 2020-08-03 22:00
@broizter did it happen on previous versions too?

**Comment by broizter** [comment] 2020-08-03 22:34
@Tyrrrz I tried downgrading to 2.1.0 and in that version only my second monitor gets affected, while in 2.2.0 both monitors both do. That seems really strange but I triple checked it.

**Comment by fgimian** [comment] 2020-08-04 01:27
On my end, and with a single monitor, I can reproduce the problem with 1.6.4.1, 2.0, 2.1 and 2.2.

**Comment by Tyrrrz** [comment] 2020-08-04 08:25
@fgimian which Windows build and which GPU do you have?

**Comment by fgimian** [comment] 2020-08-05 05:11
> @fgimian which Windows build and which GPU do you have?

I'm on Windows 10 2004 (OS Build 19041.388) and am using an NVIDIA GeForce GTX 1050 with driver version 432.00 (DCH).

Hope this helps
Fotis

**Comment by ZenitH-AT** [comment] 2020-08-05 22:29
I'm having the same issue. When I open "System" under settings, it is disabled until I disable and re-enable it. If I keep the settings page open, it will disable again the moment I switch to any sub menu in "System", but not when I go back to the main page.

* OS: Windows 10 19041.423, with the recent optional KB4568831 update
* GPU: GeForce GTX 750 Ti with the 451.67 DCH driver (most recent hotfix driver)

**Comment by Tyrrrz** [comment] 2020-08-06 10:56
Wait, are you referring to "Settings" as LightBulb's settings or something else?

**Comment by broizter** [comment] 2020-08-06 10:57
Windows 10 settings.

https://imgur.com/jSQRIPe

**Comment by Tyrrrz** [comment] 2020-08-06 11:02
Ha, all this time I thought you were saying something happened when you opened settings in LightBulb itself, not Windows. I'm actually still using an old build (I'm on LTSB) so I can't test it.

@xcasxcursex @mirh can you try this?

**Comment by xcasxcursex** [comment] 2020-08-06 22:05
Can't reproduce that here. 

Lightbulb is active and in transition before daytime at present. Open the start menu, go to settings, click system... all is normal. Tried with multiple displays,  Still all good. Also using Nvidia (1070) although not the DCH driver (I've no intention of being locked into using the windows store for my drivers) Updated Lightbulb to 2.2.0, Still good.

The one difference I have to all the reports above is that I'm not using 2004. It's 1909 here, build 18363.959
I'm overdue to update so I can give that a try in the not too distant future if you like.

Can anyone with windows pre-2004 reproduce this?

**Comment by fgimian** [comment] 2020-08-06 23:21
Just a little bit more info from my end, I updated the NVIDIA drivers using the Studio Edition from NVIDIA's website.  I'm now on version 451.77 but the problem persists.  As mentioned above, perhaps it is more in relation to the Windows version than the graphics card drivers.

**Comment by Tyrrrz** [comment] 2020-08-07 15:28
I also can't reproduce this, but I'm on ancient build 14393.

**Comment by xcasxcursex** [comment] 2020-08-07 16:07
I feel like this is a 2004 thing.

**Comment by Pbryanw** [comment] 2020-08-15 21:08
Hi, I'm also experiencing this bug, with an AMD 5700XT (latest 20.8.1 drivers). When I browse to Settings -> System, this disables Lightbulb. I'm sure this only started when I upgraded to Windows 10 2004. 

Can anyone else confirm this bug is also triggered, when you go to Settings -> Ease of Access in Windows 2004 as well? I'm not sure if any other settings are affected - these are the two that trigger this bug for me. Using Lightbulb v2.2.0.

**Comment by michalsieron** [comment] 2020-08-15 22:43
Yup, I can confirm that it happens when opening "Display" tab of "System" or "Ease of "Access" category in Windows Settings. So if you are already in one of those categories, but on different tab and then switch to "Display" it also disables LightBulb. Going into those categories disables it only, because "Display" is first tab there.

Windows 10 2004 19041.450
GTX 1050Ti 442.23

**Comment by xcasxcursex** [comment] 2020-08-16 02:45
> Can anyone with windows pre-2004 reproduce this?

**Comment by Tyrrrz** [comment] 2020-08-16 12:02
Judging by how it was reported only recently, I think there is no doubt it's a 2004 thing. The question is what can be done about it, besides enabling gamma polling. I doubt there's some system event that triggers when the settings open or the gamma is reset.

**Comment by xcasxcursex** [comment] 2020-08-16 14:33
I wonder if it could be a clash with "Night light"? From what I've read, when opening the settings dialogs, cloud sync (obviously only in effect if using a MS account and not a local one) checks the night light settings (along with the others) and I wouldn't be surprised if it applied them, too.

It's worthy of note, that the registry key which holds the night light settings, and the format used to store those settings (an undocumented binary blob) both changed in 2004 - so there's no question that night light's behaviour did change in 2004 compared to 1909.

There's a bit of chatter about it all over the place, [this spot](https://superuser.com/questions/1200222/configure-windows-creators-update-night-light-via-registry) seems to have the best generalisation of what a mess it is ;) 

So now I also wonder, if anyone is able to reproduce this while using a local account (not a Microsoft account), and/or if they can reproduce it if the appropriate registry keys for supporting the night light feature have been removed.


Another likely candidate would be monitor calibration profiles, although they''re rarely used so I doubt that one. I've also read of certain monitor drivers interfering, but again that seems too specific so I doubt that, too.


Tough one to pin down.....

**Comment by broizter** [comment] 2020-08-31 22:12
> if anyone is able to reproduce this while using a local account (not a Microsoft account)

Yes, I'm using a local account and can reproduce the issue.

**Comment by broizter** [comment] 2020-08-31 22:13
> Judging by how it was reported only recently, I think there is no doubt it's a 2004 thing. The question is what can be done about it, besides enabling gamma polling. I doubt there's some system event that triggers when the settings open or the gamma is reset.

That seems to be the solution for now. Is there any reason gamma polling is not enabled by default?

**Comment by xcasxcursex** [comment] 2020-09-01 05:07
> Is there any reason gamma polling is not enabled by default?

Performance. 

> That seems to be the solution for now.

A workaround is not a solution.... We'll find a solution soon enough...or, chances are, we'll find a bug and Microsoft will have to implement the solution ;)

**Comment by Tyrrrz** [comment] 2020-10-20 20:05
I updated my Windows, so I can now reproduce this issue too. I tried looking for power events/other messages that might represent that gamma reset, but couldn't find any. Does anyone know of any tool that could help with this?

**Comment by d4k0** [comment] 2020-10-22 23:02
I think I got a similiar problem. Since Microsoft messed up Night Light in Windows 10 1903 last year with a patch, Night Light was almost every time disabled when my screen woke up from sleep (other users also have this problem).

That's why I installed LightBulb on Windows 10 2004 a few weeks ago. It had the same problem when waking up the screen using LightBulb's default settings. However, when I activated "gamma polling" everything finally worked.

Today I installed Windows 10 20H2 and even gamma polling doesn't help anymore. I have to disable and reenable LightBulb for it to work again. I noticed that a few seconds before the screen goes to sleep the gamma setting is reset (it's like LightBulb get's deactivated, but it still shows as enabled). Night Light also still doesn't work.

Some say the graphics driver can play a role in this, but I'm always using the latest Nvidia graphics drivers and the problem still persists (in my opinion it became a bit worse with the last few drivers).

**Comment by Tyrrrz** [comment] 2020-10-23 01:12
@d4k0 if I understand correctly, you're having issues in general, not specifically when you open Settings -> System? You can try the latest CI build, I've recently done some work in this area, maybe it will help: https://github.com/Tyrrrz/LightBulb/actions/runs/323206774

**Comment by Tyrrrz** [comment] 2020-11-13 19:24
This seems to have been fixed in the latest Windows build. Can anyone confirm it's still there on Windows Version 10.0.19041.572?

**Comment by d4k0** [comment] 2020-11-14 16:48
@Tyrrrz 
Sorry for the late reply, my problem somehow got resolved after a few reboots or resetting the rights of the WindowsApps folders.

But I can confirm that something seems to have changed in the latest build. I'm on 19042.630 (Windows 10 20H2) with LightBulb 2.3.0 and I no longer have to activate gamma polling for LightBulb to stay active when my screen goes to sleep. Before, the gamma was reset when my screen went to sleep, but Lightbulb still reported that it was set to 2700K and active.

**Comment by d4k0** [comment] 2020-12-07 17:23
@Tyrrrz 
I need to update my statement. It seems to work most of the time now, but in rare cases (maybe 1-2 times a week) LightBulb is "disabled" after waking up the monitor. It seems to occur now only when the monitor has been in sleep mode for a longer time. In this case it only helps to switch the monitor off and on or to restart LightBulb.

**Comment by Tyrrrz** [comment] 2020-12-07 17:33
@d4k0 are you using LightBulb v2.3.0?

**Comment by Pbryanw** [comment] 2020-12-09 17:35
> 
> 
> This seems to have been fixed in the latest Windows build. Can anyone confirm it's still there on Windows Version 10.0.19041.572?

Sorry for the delay in replying. I can confirm that Lightbulb still disables itself when I open Settings -> System or Settings -> Ease of Access in Windows 20H2 - build 19042.662 . When I enable Gamma polling in Lightbulb, it also briefly gets disabled in the same Settings pages (for all of a second), but then quickly re-enables itself.

I'm just wondering if there's any downsides to keeping Gamma polling enabled in Lightbulb, to workaround this bug, for the time being?

**Comment by Tyrrrz** [comment] 2020-12-09 18:57
@Pbryanw gamma polling has a slight performance overhead as it essentially force-refreshes gamma every second. If you're a gamer, you may feel it in the form of input delay when playing fast-paced games. In most cases, it should not have a noticeable effect though.

**Comment by Tyrrrz** [comment] 2020-12-09 18:59
@Pbryanw also try the latest CI build and see if it also stays disabled after opening system settings (with gamma polling disabled).

https://github.com/Tyrrrz/LightBulb/actions/runs/389159502

Note: in any case, the gamma will be reset when you open the settings page, the best we can do is detect these events and refresh gamma immediately after.

**Comment by Pbryanw** [comment] 2020-12-09 19:45
@Tyrrrz  - Thank you. I've just tried the latest CI build, and with gamma polling disabled, Lightbulb still remains enabled after visiting system settings. It's also better than the 2.3 build in this respect, with gamma polling enabled, because Lightbulb only gets disabled for the briefest fraction of a second, before re-enabling itself.

Thanks again. I will stay on this build, until this fix makes its way into a future release.

**Comment by d4k0** [comment] 2020-12-10 01:14
> 
> 
> @d4k0 are you using LightBulb v2.3.0?

Yes, auto-update is enabled. Is there a way to track system events that could trigger this?

**Comment by Tyrrrz** [comment] 2020-12-10 14:14
@d4k0 it seems that the latest CI build may have fixed it

https://github.com/Tyrrrz/LightBulb/actions/runs/389159502

**Comment by Pbryanw** [comment] 2020-12-11 20:03
@Tyrrrz - Hi, there seems to be a small issue with the CI build I'm currently using. I've noticed a brief flicker when Windows is starting up (I have auto-login enabled). It's the same flicker I experience when I open System Settings. However, in this case, all that's happening is Windows is logging in. I'm just wondering what could be causing this?

**Comment by Tyrrrz** [comment] 2020-12-11 21:20
@Pbryanw the flicker is when something else resets gamma and then LightBulb sets it back to what it's supposed to be. I've noticed in latest builds of Windows 10 there are just more random things that reset gamma, so it flickers more often.

**Comment by Aman-Anas** [comment] 2020-12-13 02:33
Hi, just wanted to say that I have the same issue as OP. Will try out that CI Build.

**Comment by Aman-Anas** [comment] 2020-12-13 02:35
That CI Build does fix the issue, but it still flashes back to regular temperature for about half a second while clicking in windows settings. It's usable though 👍

**Comment by Tyrrrz** [comment] 2020-12-13 04:46
> ...but it still flashes back to regular temperature...

Like I said, there's nothing that can be done about that...

**Comment by d4k0** [comment] 2020-12-26 18:27
@Tyrrrz 
I tested the latest CI build with the latest Nvidia drivers over the last two weeks and so far this is the best version. As others have noted there is a brief flicker during some actions (like opening specific Windows settings or starting OneDrive), but that's not a big problem. Gamma polling is deactivated. Thanks!

**Comment by Tyrrrz** [comment] 2020-12-28 16:44
@d4k0 great to hear!

**Comment by Tyrrrz** [comment] 2021-03-22 11:02
Now deployed in last release.

**Closed by Tyrrrz** 2021-03-22 11:02 UTC
Labels: bug, help wanted

**Comment by fgimian** [comment] 2021-03-23 02:14
Thanks a lot, confirmed it works here too!
