### ISSUE TITLE
Plugging in new HDMI display requires restart of LightBulb

### ISSUE THREAD

**Issue by LotusOttawa** [Tyrrrz/LightBulb#146] opened 2020-03-26 14:17 UTC
Hi,

When I plug in an HDMI display the gamma settings don't take effect on both the new and original screen - even with Gamma polling and preview. Only way to fix it is to restart LightBulb.

**Comment by Tyrrrz** [comment] 2020-03-26 14:24
Hi.
This is a known issue that is fixed for the next release.
Duplicate of #142

**Closed** 2020-04-19 14:09 UTC
Labels: duplicate
