### ISSUE TITLE
Flagged as malware?

### ISSUE THREAD

**Issue by steveyeu** [Tyrrrz/LightBulb#193] opened 2021-02-20 04:50 UTC
Checking the most recent release obtained from GitHub is suggesting there may be malware present:

https://www.virustotal.com/gui/file/640dbcf52d6364396eb933d74d4a5d6473bab6aaf71d594092810df1a9c01f38/detection

Can anyone confirm if this is the case or if they are false positives?

**Comment by Tyrrrz** [comment] 2021-02-22 00:17
Duplicate of #185

**Closed by Tyrrrz** 2021-02-22 00:17 UTC
Labels: duplicate
