### ISSUE TITLE
Color jitter abnormally if detect location automatically base on IP

### ISSUE THREAD

**Issue by wswday** [Tyrrrz/LightBulb#113] opened 2019-11-14 08:14 UTC
Thank your great work.
I found a bug when using preview mode.

[Portable Version](https://github.com/Tyrrrz/LightBulb/commit/ffa31ada917c41523c049413e7ffc47a678766b1/checks?check_suite_id=309312468)

Reproduce:
Preview after detect location automatically base on IP, appear at about 3:00 AM.
detected location is 22.5333, 114.1333

If set location as 22.5333, 114.1333(manually, not detect automatically), this bug will not appear

![109399515610366363442b5fc31d8ad](https://user-images.githubusercontent.com/13781208/68838673-0d1fcd00-06fa-11ea-8c07-a3f9580271eb.jpg)

**Comment by Tyrrrz** [comment] 2019-11-14 08:46
Hi, thanks for trying out the CI build.

This is interesting. What exactly do you mean by jittering? I can see from your photo that the background is yellow, but it could've been a bug that was fixed in [this](https://github.com/Tyrrrz/LightBulb/commit/5b31c042ebd86b5cd08629eca5b5e28de72af01f) commit.

Also, it seems to say 9005 K / 114 % which looks abnormal. Was it set manually or is it part of the bug?

Can you record a video depicting the jitter so it's easier to understand what's happening?

**Comment by wswday** [comment] 2019-11-14 09:00
Hi @Tyrrrz 
Temperoture and brightness is defalt, only setting location by automatical detection.
They became 9005 K / 114 % when preview

**Comment by Tyrrrz** [comment] 2019-11-14 09:05
Can you please send me your configuration file that leads to jitter and configuration file that works fine?

If you used portable, it will be in the same directory as the .exe file. If you used installer, you will find configuration file in "C:\Users\Tyrrrz\AppData\Roaming\LightBulb\Settings.dat".

**Comment by wswday** [comment] 2019-11-14 09:24
config leads to jitter
{
  "IsFirstTimeExperienceEnabled": false,
  "NightConfiguration": {
    "Temperature": 3900.0,
    "Brightness": 0.85
  },
  "DayConfiguration": {
    "Temperature": 6600.0,
    "Brightness": 1.0
  },
  "ConfigurationTransitionDuration": "01:30:00",
  "IsManualSunriseSunsetEnabled": false,
  "ManualSunriseTime": "07:20:00",
  "ManualSunsetTime": "16:30:00",
  "Location": {
    "Latitude": 22.5333,
    "Longitude": 114.1333
  },
  "IsDefaultToDayConfigurationEnabled": false,
  "IsGammaSmoothingEnabled": true,
  "IsPauseWhenFullScreenEnabled": false,
  "ToggleHotKey": {
    "Key": 0,
    "Modifiers": 0
  }
}

**Comment by wswday** [comment] 2019-11-14 09:25
config works fine
{
  "IsFirstTimeExperienceEnabled": false,
  "NightConfiguration": {
    "Temperature": 3900.0,
    "Brightness": 0.85
  },
  "DayConfiguration": {
    "Temperature": 6600.0,
    "Brightness": 1.0
  },
  "ConfigurationTransitionDuration": "01:30:00",
  "IsManualSunriseSunsetEnabled": false,
  "ManualSunriseTime": "07:20:00",
  "ManualSunsetTime": "16:30:00",
  "Location": null,
  "IsDefaultToDayConfigurationEnabled": false,
  "IsGammaSmoothingEnabled": true,
  "IsPauseWhenFullScreenEnabled": false,
  "ToggleHotKey": {
    "Key": 0,
    "Modifiers": 0
  }
}

**Comment by Tyrrrz** [comment] 2019-11-14 09:26
Thanks. It looks like in the second one location is actually not set.

**Comment by wswday** [comment] 2019-11-14 09:28
Yes, only location is different.
![compare](https://user-images.githubusercontent.com/13781208/68844027-0dbd6100-0704-11ea-92b9-0cd027c71e7c.png)

**Comment by wswday** [comment] 2019-11-14 10:18
Hi, @Tyrrrz 
BTW, location will not be save, if fill location manually and select save button.
It could be better if restrict user must select detecting automatically or setting manually.
![屏幕截图(9)](https://user-images.githubusercontent.com/13781208/68848323-16fdfc00-070b-11ea-9dc6-f815d8ee200a.png)

**Comment by Tyrrrz** [comment] 2019-11-14 10:21
Yeah, you need to press the checkmark. I know it's not optimal UX.

**Comment by Tyrrrz** [comment] 2019-11-15 16:14
Managed to reproduce some bug but I'm not sure if that's the same one.
I can see that using those coordinates, it calculates sunrise and sunset incorrectly, but your screenshot shows seemingly valid sunrise/sunset though.
![image](https://user-images.githubusercontent.com/1935960/68957953-c9999180-07d3-11ea-8395-b285512bb06d.png)

**Comment by Tyrrrz** [comment] 2019-11-15 16:51
Should be fixed now

**Closed by Tyrrrz** 2019-11-15 16:51 UTC
Labels: bug
