### ISSUE TITLE
Settings reset?

### ISSUE THREAD

**Issue by coolguy222** [Tyrrrz/LightBulb#63] opened 2017-12-10 17:56 UTC
About once a week on startup, Lightbulb's settings are completely reset to their default. (Windows 7 64-bit)

Is there a configuration setting I'm missing or is this a known issue? I have the temperature set to a static value at all times.

**Comment by Tyrrrz** [comment] 2017-12-10 18:11
Most likely duplicate of #62

**Closed by Tyrrrz** 2017-12-10 18:11 UTC
Labels: duplicate

**Comment by JJRcop** [comment] 2018-09-21 21:14
This is [my comment](https://github.com/Tyrrrz/LightBulb/issues/62#issuecomment-423330362) on #62

> I've found a workaround is to change your settings to how you like them, then right-click on the Configuration.dat file in Windows Explorer and check the Read Only option, this prevents LightBulb from writing to the file at all.
> ![image](https://user-images.githubusercontent.com/5211576/45846562-1976e880-bcf6-11e8-96bc-27bbe2ec3e64.png)
