### ISSUE TITLE
Latest (2.3.1) update slows down computer/skips frames

### ISSUE THREAD

**Issue by vondyhaar** [Tyrrrz/LightBulb#198] opened 2021-03-21 21:46 UTC
My computer seems to not like the latest update, the system looks as if it's stuttering/low on fps. 
Task Manager shows nothing out of the ordinary. 2.2 and below work nicely.
I'm on Windows 10 1607.

**Comment by weiw11** [comment] 2021-03-21 23:18
Have the same issue as well. When using VLC to play videos, it also causes audio de-sync.

**Comment by ARDEACT** [comment] 2021-03-22 00:35
THIS THIS THIS. I've been finding out all day what is causing my PC to have audio crackling and stuttering, I remembered I updated lightbulb this morning. When I terminated the process, all normal! Something happened on this update, please fix!

**Comment by Tyrrrz** [comment] 2021-03-22 05:12
That sounds bad :/

Note that you can revert back to 2.3.0 by:
1. Disabling autoupdates in settings
2. Downloading and installing the [previous version from releases](https://github.com/Tyrrrz/LightBulb/releases/tag/2.3)

It looks like the more aggressive gamma invalidation that was added in the last version doesn't bode well with some of the users. The release was tested by a few people (including myself) and it worked well. Will have to take a look into it.

**Comment by svenbit** [comment] 2021-03-22 09:26
I have the same issue with version 2.3.1, it causes slow down and audio to stutter.

Task Manager also shows that dwm.exe (Desktop Window Manager) seems to be using higher CPU usage than usual when LightBulb is open/enabled. CPU usage for dwm.exe seems to be back to normal when LightBulb is closed (exit), disable doesn't seems to work.

**Comment by ARDEACT** [comment] 2021-03-22 16:24
I should state that I'm using a Ryzen system with a DAC: Ryzen 7 2700 and Focusrite Scarlett Solo

**Comment by odensc** [comment] 2021-03-22 20:39
Same issue here since 2.3.1, frames stuttering on desktop/in-game, and audio crackling. 

* Ryzen 5900x
* RTX 3080 - Nvidia drivers 461.92
* Windows 10 Pro 20H2

If anyone with the issue can post the same info we may be able to see if there's a common thread.

**Comment by ARDEACT** [comment] 2021-03-22 20:41
Those poor individuals who haven't realized that Lightbulb is the culprit are probably going crazy.

**Comment by weiw11** [comment] 2021-03-22 21:30
@Tyrrrz I uninstalled V2.3.0 and installed V2.3.1 directly from the release page and it's working fine for me right now. Will update if I experience similar issues.

Maybe it's an issue with the configuration file from the update or an issue with the auto update feature?

**Comment by Tyrrrz** [comment] 2021-03-22 23:47
> @Tyrrrz I uninstalled V2.3.0 and installed V2.3.1 directly from the release page and it's working fine for me right now. Will update if I experience similar issues.
> 
> Maybe it's an issue with the configuration file from the update or an issue with the auto update feature?

I really doubt it.

Can you also post your specs please?

**Comment by weiw11** [comment] 2021-03-22 23:56
8700k
1070Ti
Windows 10 64-bit 20H2

**Comment by ljrafols** [comment] 2021-03-25 19:37
I can corroborate with previous comments about 2.3.1 causing stuttering issues. Uninstalling that version and reinstalling 2.3.0 with autoupdate disabled seems to have fixed the issue for now. Seems to be independent of drivers, as rolling back from the latest (461.92) to the previous drivers I used (460.79) and 460.89 had no change to the stuttering problem.

RE: accent colour changes, I did not change my accent colour nor have it set to automatically change based on background, so I do not believe the problem explicitly lies there.

Specs as followed.
Ryzen 5 3600, Stock
MSI GTX 1080, Stock
Windows 10 x64 1909/19H2

**Comment by weiw11** [comment] 2021-03-26 03:23
What I meant was maybe the screen warming with the latest update by forcing it to repeatedly force refresh gamma for a short period creates the same issue as the accent color change. This would kind of make sense as the frame time spikes once in a while based on the chart provided by RTSS, but it's just my speculation.

**Comment by DigiOhhh** [comment] 2021-03-26 11:57
I remember having a similar issue with 2.3.0, but I didn't even suspect LightBulb to be the culprit
in my case, I get audio crackling especially during night, when LightBulb has changed the screen brightness and temperature.


My laptop is pretty old.

Intel i3 M 380
Nvidia GT 540M
Windows 7 x64

I also had the same symptoms on Windows 10

**Comment by d3xMachina** [comment] 2021-03-26 15:08
I'm having this issue too. I'm on windows 20H2.
Lightbulb (latest version) worked like a charm for a few months and then my computer started to stutter. I didn't update lightbulb nor my graphics drivers.
So I tried to update my nvidia driver and it didn't change anything. I tried to exit all third-party programs running on my computer to find the culprit and I pinned it down to lightbulb.
Lightbulb makes my dwm.exe (the processus for desktop composition) go from 0% CPU to a steady 3% (it's a lot since I have a ryzen 3900x) which causes the stutter.

**Comment by vekuda** [comment] 2021-03-27 09:31
> 
> 
> Have the same issue as well. When using VLC to play videos, it also causes audio de-sync.

Same here: I have been experiencing it on mpv and YouTube as well. 
After 5-6 minutes of playback it happens that sound and footage go completely out of sync.

I have been lucky enough to remember that I had updated LightBulb a few days ago...

**Comment by eXmendiC** [comment] 2021-03-27 18:55
Same for me: Ryzen 5900X + GeForce GTX 1080.
I didn't even notice a high CPU or GPU usage with version 2.3.1. I had many frame drops with mpv and also lags in Genshin Impact. I already thought that maybe my GPU slowly conks out. It's really a relieve that this isn't the case. However, I really wonder how an update can affect it _that_ bad.

**Comment by djcyrax** [comment] 2021-03-28 10:05
I've been going crazy trying to figure out why my audio was stuttering and crackling. finally I decided to close LightBulb and it went away. Please fix this issue.

**Comment by M-O-Marmalade** [comment] 2021-03-30 21:53
Happening to me too. I was installing Windows Updates, graphics driver updates, unplugging external HDDs and such, then finally killed some processes (which should have been the first step lol), and upon killing Lightbulb, lag immediately gone :open_mouth:

**Comment by Kyuhaku** [comment] 2021-04-03 01:52
Interesting, I was suffering from this as well. I was thinking it was NVidia Drivers as I was using LatencyMon and that was usually the main cause (nvlddmkm.sys). Weird thing is if the GPU drivers are disabled in device manager or using Microsoft Basic Adapter, I don't see any issues when using Lightbulb even on version 2.3.1  

Ryzen 5 3600 | NVidia RTX 3060 Ti

**Comment by deskilln** [comment] 2021-04-04 17:59
it all makes sense now

aaaaaaaaaaaaaa

**Comment by bulhi** [comment] 2021-04-08 18:11
To add my two cents, I have an older laptop with Windows 8 which is mostly used just by my girlfriend for web browsing, and it was actually the "Client Server Runtime Process" that suddenly started eating around 5-10% of CPU. Same as others here, after fiddling with stuff, drivers, blaming my poor gf for infecting the computer with a virus etc. I eventually found out killing Lightbulb sent it back to zero :relieved: Downgrading to 2.3 helped.

**Comment by edscript0** [comment] 2021-04-15 12:21
> ivers as I

Same, I re-installed the drivers, now everything makes sense!

**Comment by PanoptesDreams** [comment] 2021-04-16 23:40
Same issue.
CPU - Intel Pentium G4560
GPU - GTX 1060 3GB
20GB RAM
Win 10 - 20H2
LightBulb 2.3.1

(msg/reply if other details wanted)

**Comment by Tyrrrz** [comment] 2021-04-27 14:00
Judging by the comments (thanks btw), it seems that this issue only manifests with Nvidia GPUs. Which would explain why I don't experience it myself, given that I have a Radeon GPU.

![image](https://user-images.githubusercontent.com/1935960/116253068-fec64500-a724-11eb-9e2a-13e463a6986e.png)
![image](https://user-images.githubusercontent.com/1935960/116253110-0be33400-a725-11eb-8ffb-33ef7019f540.png)
![image](https://user-images.githubusercontent.com/1935960/116253156-143b6f00-a725-11eb-907d-0194fa128cee.png)
![image](https://user-images.githubusercontent.com/1935960/116253207-1dc4d700-a725-11eb-8346-82d4eec7c75c.png)
![image](https://user-images.githubusercontent.com/1935960/116253258-2ae1c600-a725-11eb-9c9d-c5842de8c96a.png)
![image](https://user-images.githubusercontent.com/1935960/116253318-3af9a580-a725-11eb-877e-3eb5750e3ea8.png)
![image](https://user-images.githubusercontent.com/1935960/116253354-43ea7700-a725-11eb-9a5d-a1e50d2137e7.png)

Now, seeing as everyone said that it only happens on the very last version, the only culprit seems to be this specific commit: https://github.com/Tyrrrz/LightBulb/commit/772a12a66e314ac0f49b21d0668d2ef775ca2854

My guess is that something about Nvidia drivers makes LightBulb think that the gamma or device context is constantly invalidated, which makes it constantly force-refresh gamma at a very high rate, causing stutter. I'll see if I can figure this out in the blind, otherwise I'll have to find an Nvidia GPU somewhere to debug.

**Comment by Tyrrrz** [comment] 2021-04-27 14:58
Can someone try this CI build? https://github.com/Tyrrrz/LightBulb/actions/runs/789494647

Portable: https://github.com/Tyrrrz/LightBulb/suites/2594818266/artifacts/56698218
Installer: https://github.com/Tyrrrz/LightBulb/suites/2594818266/artifacts/56698219

**Comment by L--U--P--U--S** [comment] 2021-04-28 21:36
Installed the build, but I don't know how to exactly trigger the described behaviour. Hence, it will take some days to report back.

**Comment by odensc** [comment] 2021-04-28 21:42
@Tyrrrz I don't see any stuttering/frame drops with this version. With 2.3.1 those effects would start immediately upon opening LightBulb. Seems fixed to me.

**Comment by PanoptesDreams** [comment] 2021-04-29 00:59
> Can someone try this CI build? https://github.com/Tyrrrz/LightBulb/actions/runs/789537034
> 
> Portable: https://github.com/Tyrrrz/LightBulb/suites/2594951280/artifacts/56703031
> Installer: https://github.com/Tyrrrz/LightBulb/suites/2594951280/artifacts/56703032
> 
> Edit: changed links

Tried the portable build, seems to work fine. Will keep it running and report back if there are any issues.

**Comment by joscha999** [comment] 2021-05-04 00:22
To add to this thread I also just noticed this - had lags since the last few days.
I think this is a mix of a Handle/Memory leak but I'm not quite sure (at least for the Handles part).

I just killed the app with about 50GB of RAM usage - this was paged RAM so it didn't show up on the normal task manager but checking via the resource monitor showed ~51GB and closing the app released all of it.
I also noticed a specific service reaching the Handle limit of Windows (~16 million), can't remember the name but I think it was something started by or with LightBulb.

Note: I usually let my PC run for several days and only hibernate it at night - this may make this whole problem worse (or really only be the reason it shows up for some and not others).

Now switched to 2.3.0, I'll let ya'll know if this also happens on that version.
Hope this information may help you finding the issue @Tyrrrz, thanks for the work on LightBulb!

**Comment by L--U--P--U--S** [comment] 2021-05-07 17:46
> Installed the build, but I don't know how to exactly trigger the described behaviour. Hence, it will take some days to report back.

So far, looks good for me. No more stutter with https://github.com/Tyrrrz/LightBulb/suites/2594951280/artifacts/56703032

**Comment by DinushaJ** [comment] 2021-05-09 03:12
> Those poor individuals who haven't realized that Lightbulb is the culprit are probably going crazy.

I only just figured it out after this whole time... Was actually about to reset my system

**Comment by Hamish-GJP** [comment] 2021-05-12 18:51
I was severely impacted by this issue. Tracking down the source caused me to tunnel through to my reptilian brain with a Phillips head screwdriver.

After several days running the CI build, I'm happy to report that all is well, even when working with demanding Cubase projects using ASIO.

My head hurts.

**Comment by V3rzeT** [comment] 2021-06-07 14:56
OH MY GOD, I was trying to figure this out for the past ~2 weeks, I even contacted Microsoft because of it. It has affected me A LOT.
The issue started around 2 hours from boot up, and I found the cause by manually terminating each process that wasn't windows related until it stopped...
The program is great, but please fix this!

**Comment by Tyrrrz** [comment] 2021-06-08 21:32
Released a new version. Sorry it took so long, was blocked by a dependency that I needed to get into this version.

**Closed by Tyrrrz** 2021-06-08 21:32 UTC
Labels: bug, help wanted
