### ISSUE TITLE
Option to automatically pause when specific applications are in focus

### ISSUE THREAD

**Issue by Yirg** [Tyrrrz/LightBulb#89] opened 2018-11-03 01:04 UTC
I just discovered LightBulb and like it very much. One feature I'm missing though is an option to pause it automatically if certain application are in focus, in my case I would use it with image editing/viewing applications and video players. With these application I usually care a lot about color accuracy and would prefer to have my default (calibrated) color profile active.

Thanks in advance!

**Comment by Tyrrrz** [comment] 2018-11-03 11:49
Thanks for the suggestion.
This is a duplicate of #39

**Closed by Tyrrrz** 2018-11-03 11:49 UTC
Labels: duplicate
