### ISSUE TITLE
Literally does nothing at all whatsoever

### ISSUE THREAD

**Issue by turkeyphant** [Tyrrrz/LightBulb#99] opened 2019-06-09 21:47 UTC
Windows 10.
Installed with chocolatey.
Neither previews nor actual settings make any colour change differences on any of three monitors.

**Comment by turkeyphant** [comment] 2019-06-09 21:49
Same issue with portable version.

**Comment by dolevu** [comment] 2019-06-11 11:21
I have the same issues, but randomly after restarting
Windows 10, 1903

**Comment by turkeyphant** [comment] 2019-06-11 11:37
I couldn't get it to work at all. I installed it to start with because one of my monitors was not being affected by f.lux so I tried LightBulb, Iris and the build-in Windows tool.

None of these worked either and it turned out that they started conflicting with each other. Completely removing all three with CCleaner and reinstalling LIghtBulb still didn't work but it did fix my f.lux install which does work in Windows still.

**Comment by broizter** [comment] 2019-06-30 21:57
I can concur that this program no longer does anything. Probably related to Windows updates.

**Comment by broizter** [comment] 2019-07-07 21:52
Did not help unfortunately.

**Comment by normandparatte** [comment] 2019-08-08 07:54
Same issue when I have updated my Windows 10 on the latest actual version 1903

**Comment by mirh** [comment] 2019-08-31 20:05
Try 
https://ci.appveyor.com/project/Tyrrrz/LightBulb/build/artifacts

**Comment by Tyrrrz** [comment] 2019-11-08 16:52
Closing this because it's most likely a duplicate of #100

**Closed by Tyrrrz** 2019-11-08 16:52 UTC
Labels: duplicate
