### ISSUE TITLE
disable for app choice

### ISSUE THREAD

**Issue by depfryer** [Tyrrrz/LightBulb#92] opened 2019-01-09 06:11 UTC
i'm using app with dark Theme (monokai) so lightBulb is only her for White killer screen
and i want to know if it's possible to exclude some app or if it's a possible evolve 
Thanks ;p

**Comment by Tyrrrz** [comment] 2019-01-09 10:04
Duplicate of #39

**Closed by Tyrrrz** 2019-01-09 10:04 UTC
Labels: duplicate
