### ISSUE TITLE
Lightbulb causing other apps to flicker when gamma polling enabled, even with Lightbulb disabled

### ISSUE THREAD

**Issue by BenKennish** [Tyrrrz/LightBulb#321] opened 2024-07-17 18:51 UTC
### Version

2.5.3

### Platform

Windows 10

### Steps to reproduce

Load LightBulb
Enable Gamma Polling
Load up Task Manager and it is flashing/flickering on a regular interval of about once a second

### Details

With Lightbulb loaded and with Gamma Polling enabled, apps like Task Manager and HWiNFO64 experiencing regular flickering (seemingly once per second).  This happens regardless of whether LightBulb is enabled or not, e.g. using the keyboard shortcut to "Toggle Lightbulb" or using the system tray icon to "Disable for 5 minutes".  Shutting down LightBulb or disabling Gamma Polling is the only way to stop the flickering.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment] 2024-07-17 20:06
With gamma polling enabled, LightBulb will refresh gamma every second, even if it's disabled. This is done to facilitate the "disable to day-time configuration" option.

Regardless of that, however, flickering indicates that there's something else in your system attempting to override the monitor gamma. It can be another app or, in some cases, the operating system itself. In my personal tests, I do not experience any flickering with Task Manager, so the issue is that some other running app is trying to control monitor gamma in parallel to LightBulb.

**Comment by BenKennish** [comment] 2024-07-22 15:31
Ah ok thank you for that.  When it happens again, I will try closing all other apps and see if I can get the flickering to stop.

**Comment by BenKennish** [comment] 2024-07-24 00:06
Weirdly, I've noticed that the blue light filter is sometimes removed temporarily when i click the Action Center icon in the very right of the Windows Task Tray (to the right of the clock) and then resumes when I close it.  However I am not using Nigh Light so I'm not sure what's going on

**Comment by Tyrrrz** [comment] 2024-07-24 16:15
Yeah it does that. Also happens when you open the Display settings in the Control Panel.

**Comment by BenKennish** [comment] 2024-07-24 19:06
Ah so that's expected to happen for everyone and isn't a clue as to what could be causing my app flickering issue?

**Comment by Tyrrrz** [comment] 2024-07-24 22:13
Nope. Those windows are just known to reset monitor state when you bring them to the foreground. LightBulb automatically refreshes gamma when you change active windows, which is why it reverts back after you close the window.

**Comment by BenKennish** [comment] 2024-07-24 22:35
Ah very interesting.  Thanks.  My search for the app that's causing the flickering continues... 😅

**Comment by Tyrrrz** [comment] 2024-08-07 00:26
Yeah it might be difficult. Some common culprits are motherboard/peripheral "control panel" apps, such as the MSI or Razer app.

Closing the issue as it's not a problem in LightBulb, but just the way gamma manipulation works in Windows.

**Closed by Tyrrrz** 2024-08-07 00:26 UTC
Labels: invalid
